"""add users, patients, medical_records, xray_images, ai_analysis_results tables

Revision ID: 45d9d061825c
Revises: 
Create Date: 2026-08-26 06:39:53.576131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d9d061825c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False, comment='환자 성명'),
    sa.Column('age', sa.SmallInteger(), nullable=False, comment='환자 나이'),
    sa.Column('gender', sa.Enum('M', 'F', name='genderenum', native_enum=False, length=10), nullable=True, comment='환자 성별'),
    sa.Column('phone', sa.String(length=11), nullable=False, comment='환자 연락처, 국내 전화번호로 한정'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False, comment='환자 등록 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='환자 정보 수정 일시'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='평문 저장 X -> 해시화 된 비밀번호 저장'),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False, comment='유저 휴대폰 번호'),
    sa.Column('gender', sa.Enum('M', 'F', name='genderenum', native_enum=False, length=10), nullable=False, comment='성별 선택'),
    sa.Column('department', sa.Enum('MEDICAL', 'DEV', 'RESEARCH', name='departmentenum', native_enum=False, length=20), nullable=False, comment='부서 선택'),
    sa.Column('role', sa.Enum('PENDING', 'STAFF', 'ADMIN', name='roleenum', native_enum=False, length=20), nullable=False, comment='부여된 역할 권한'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False, comment='계정 활성화 여부'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False, comment='유저 생성 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='유저 정보 수정 일시'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('medical_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.BigInteger(), nullable=False),
    sa.Column('chart_number', sa.String(length=50), nullable=False, comment='차트 번호'),
    sa.Column('symptoms', sa.Text(), nullable=False, comment='증상'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False, comment='진료 기록 등록 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='진료 기록 수정 일시'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chart_number')
    )
    op.create_table('ai_analysis_results',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('is_pneumonia', sa.Boolean(), nullable=False, comment='AI 모델의 폐렴 여부 예측 결과'),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=False, comment='예측 신뢰도(확률, %)'),
    sa.Column('heatmap_url', sa.String(length=255), nullable=False, comment='AI가 근거로 삼은 부위를 표시한 히트맵 이미지 URL'),
    sa.Column('ai_model', sa.String(length=50), nullable=False, comment='분석에 사용된 AI 모델명/버전'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False, comment='분석 결과 생성 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='분석 결과 수정 일시'),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('xray_images',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('record_id', sa.BigInteger(), nullable=False),
    sa.Column('uploader_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=2048), nullable=False, comment='업로드된 X-Ray 이미지 URL'),
    sa.Column('shooting_datetime', sa.DateTime(), nullable=False, comment='X-Ray 촬영 일시'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False, comment='이미지 등록(업로드) 일시'),
    sa.ForeignKeyConstraint(['record_id'], ['medical_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('xray_images')
    op.drop_table('ai_analysis_results')
    op.drop_table('medical_records')
    op.drop_table('users')
    op.drop_table('patients')
    # ### end Alembic commands ###
